#!/usr/bin/env bash
#
# Credit where it's due: This script was generated by Claude Sonnet 4.6.
#
# =============================================================================
# setup-bind9.sh — Install and configure BIND9 on a Proxmox/Debian host
# as a recursive resolver + dynamic DNS zone with nsupdate support.
#
# Usage:
#   ./setup-bind9.sh [OPTIONS]
#
# Options:
#   -d, --domain DOMAIN       Dynamic DNS zone name       (default: home.lan)
#   -i, --listen-ip IP        IP address BIND should listen on (default: auto-detected LAN IP)
#   -n, --subnet SUBNET       Allow-query/recursion subnet (default: auto-detected from listen-ip)
#   -u, --upstream DNS_IP     Upstream forwarder IP        (default: 8.8.8.8)
#   -k, --key-secret SECRET   TSIG key secret (base64)     (default: auto-generated)
#   -K, --key-name NAME       TSIG key name                (default: ddns-key)
#   -y, --yes                 Skip confirmation prompt
#   -h, --help                Show this help message
#
# If --listen-ip is not provided, the script attempts to auto-detect the
# primary non-loopback IPv4 address.
# =============================================================================

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────────
DOMAIN="home.lan"
UPSTREAM_DNS="8.8.8.8"
KEY_NAME="ddns-key"
KEY_SECRET=""        # empty = auto-generate
LISTEN_IP=""         # empty = auto-detect
SUBNET=""            # empty = derive from LISTEN_IP
SKIP_CONFIRM=false

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
header()  { echo -e "\n${BOLD}${CYAN}==> $*${RESET}"; }

# ── Argument parsing ──────────────────────────────────────────────────────────
usage() {
    grep '^#' "$0" | grep -v '#!/' | sed 's/^# \?//'
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -d|--domain)      DOMAIN="$2";       shift 2 ;;
        -i|--listen-ip)   LISTEN_IP="$2";    shift 2 ;;
        -n|--subnet)      SUBNET="$2";       shift 2 ;;
        -u|--upstream)    UPSTREAM_DNS="$2"; shift 2 ;;
        -k|--key-secret)  KEY_SECRET="$2";   shift 2 ;;
        -K|--key-name)    KEY_NAME="$2";     shift 2 ;;
        -y|--yes)         SKIP_CONFIRM=true; shift ;;
        -h|--help)        usage ;;
        *) error "Unknown option: $1. Use --help for usage." ;;
    esac
done

# ── Pre-flight checks ─────────────────────────────────────────────────────────
header "Pre-flight checks"

[[ $EUID -eq 0 ]] || error "This script must be run as root."

command -v apt-get &>/dev/null || error "This script requires apt-get (Debian/Ubuntu/Proxmox)."

# Auto-detect listen IP if not provided
if [[ -z "$LISTEN_IP" ]]; then
    LISTEN_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
    [[ -n "$LISTEN_IP" ]] || error "Could not auto-detect LAN IP. Please specify with --listen-ip."
    info "Auto-detected listen IP: ${BOLD}$LISTEN_IP${RESET}"
fi

# Derive /24 subnet from listen IP if not provided
if [[ -z "$SUBNET" ]]; then
    SUBNET=$(echo "$LISTEN_IP" | awk -F. '{print $1"."$2"."$3".0/24"}')
    info "Derived subnet: ${BOLD}$SUBNET${RESET}"
fi

# Auto-generate TSIG secret if not provided
if [[ -z "$KEY_SECRET" ]]; then
    KEY_SECRET=$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 | tr -d '\n')
    info "Auto-generated TSIG key secret."
fi

success "Pre-flight checks passed."

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}Configuration summary:${RESET}"
echo -e "  Domain (zone):   ${BOLD}$DOMAIN${RESET}"
echo -e "  Listen IP:       ${BOLD}$LISTEN_IP${RESET}"
echo -e "  Allow subnet:    ${BOLD}$SUBNET${RESET}"
echo -e "  Upstream DNS:    ${BOLD}$UPSTREAM_DNS${RESET}"
echo -e "  TSIG key name:   ${BOLD}$KEY_NAME${RESET}"
echo -e "  TSIG secret:     ${BOLD}$KEY_SECRET${RESET}"
echo
if [[ "$SKIP_CONFIRM" == true ]]; then
    info "Skipping confirmation (--yes flag set)."
else
    read -r -p "Proceed with installation? [y/N] " confirm
    [[ "${confirm,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

# ── Install packages ──────────────────────────────────────────────────────────
header "Installing BIND9"
apt-get update -qq
apt-get install -y bind9 bind9utils dnsutils
success "BIND9 installed."

# ── Write TSIG key file ───────────────────────────────────────────────────────
header "Writing TSIG key file"
KEYFILE="/etc/bind/ddns.key"

cat > "$KEYFILE" <<EOF
key "${KEY_NAME}" {
    algorithm hmac-sha256;
    secret "${KEY_SECRET}";
};
EOF

chown root:bind "$KEYFILE"
chmod 640 "$KEYFILE"
success "TSIG key written to $KEYFILE"

# ── Write named.conf.options ──────────────────────────────────────────────────
header "Configuring named.conf.options"

cat > /etc/bind/named.conf.options <<EOF
options {
    directory "/var/cache/bind";

    // ── Recursive resolver ───────────────────────────────────────────────────
    recursion yes;
    allow-recursion { 127.0.0.1; ::1; ${SUBNET}; };
    allow-query    { 127.0.0.1; ::1; ${SUBNET}; };

    // ── Forwarders ───────────────────────────────────────────────────────────
    forwarders { ${UPSTREAM_DNS}; };
    forward first;
    empty-zones-enable yes;

    // ── DNSSEC ───────────────────────────────────────────────────────────────
    dnssec-validation auto;

    // ── Listen addresses ─────────────────────────────────────────────────────
    listen-on { 127.0.0.1; ${LISTEN_IP}; };
    listen-on-v6 { ::1; };

    auth-nxdomain no;
};
EOF

success "named.conf.options written."

# ── Write named.conf.local ────────────────────────────────────────────────────
header "Configuring named.conf.local"

cat > /etc/bind/named.conf.local <<EOF
include "/etc/bind/ddns.key";

zone "${DOMAIN}" {
    type primary;
    file "/var/lib/bind/${DOMAIN}.db";
    allow-update { key "${KEY_NAME}"; };
    allow-query  { any; };
    allow-transfer { none; };
    forwarders {};
};
EOF

success "named.conf.local written."

# ── Create initial zone file ──────────────────────────────────────────────────
header "Creating initial zone file"
ZONEFILE="/var/lib/bind/${DOMAIN}.db"

# Generate a serial based on today's date
SERIAL=$(date +%Y%m%d01)

cat > "$ZONEFILE" <<EOF
\$ORIGIN ${DOMAIN}.
\$TTL 300

@   IN  SOA ns1.${DOMAIN}. admin.${DOMAIN}. (
            ${SERIAL} ; serial
            3600      ; refresh
            900       ; retry
            604800    ; expire
            300 )     ; negative cache TTL

    IN  NS  ns1.${DOMAIN}.

ns1 IN  A   ${LISTEN_IP}
EOF

chown bind:bind "$ZONEFILE"
chmod 644 "$ZONEFILE"
success "Zone file written to $ZONEFILE"

# ── systemd override: Type=forking so systemd doesn't wait on notify socket ───
# Named cannot signal systemd readiness via the notify socket due to a kernel/
# AppArmor ABI mismatch on Proxmox. Using Type=forking bypasses this entirely.
header "Configuring systemd service override for named"
mkdir -p /etc/systemd/system/named.service.d

cat > /etc/systemd/system/named.service.d/override.conf <<'EOF'
[Service]
Type=forking
NotifyAccess=none
ExecStart=
ExecStart=/usr/sbin/named -u bind
EOF

systemctl daemon-reload
success "systemd override written — named will use Type=forking."

# ── Validate configuration ────────────────────────────────────────────────────
header "Validating configuration"
named-checkconf && success "named-checkconf passed."
named-checkzone "$DOMAIN" "$ZONEFILE" && success "named-checkzone passed."

# ── Enable and restart BIND9 ──────────────────────────────────────────────────
header "Starting BIND9"
systemctl enable named
systemctl restart named
sleep 2
systemctl is-active --quiet named && success "named is running." || error "named failed to start. Check: journalctl -u named"

# ── Write client key file ─────────────────────────────────────────────────────
header "Writing client key file"
CLIENT_KEYFILE="/root/ddns-client.key"

cat > "$CLIENT_KEYFILE" <<EOF
key "${KEY_NAME}" {
    algorithm hmac-sha256;
    secret "${KEY_SECRET}";
};
EOF

chmod 600 "$CLIENT_KEYFILE"
success "Client key written to $CLIENT_KEYFILE — copy this to your nsupdate clients."

# ── Write example nsupdate script ─────────────────────────────────────────────
header "Writing example nsupdate client script"
CLIENT_SCRIPT="/root/ddns-register.sh"

cat > "$CLIENT_SCRIPT" <<EOF
#!/usr/bin/env bash
# Example nsupdate registration script.
# Copy this and /root/ddns-client.key to each host that needs dynamic DNS.
#
# Usage: ./ddns-register.sh [hostname] [ip]
#   hostname defaults to \$(hostname -s)
#   ip       defaults to the primary LAN IP

set -euo pipefail

KEYFILE="\${KEYFILE:-./ddns-client.key}"
DNS_SERVER="${LISTEN_IP}"
ZONE="${DOMAIN}"
FQDN="\${1:-\$(hostname -s)}.\${ZONE}"
IP="\${2:-\$(ip -4 route get 1.1.1.1 | awk '{for(i=1;i<=NF;i++) if(\$i=="src"){print \$(i+1);exit}}')}"
TTL=300

echo "Registering \${FQDN} -> \${IP} on \${DNS_SERVER}"

nsupdate -k "\$KEYFILE" <<NSEOF
server \${DNS_SERVER}
zone \${ZONE}
update delete \${FQDN} A
update add    \${FQDN} \${TTL} A \${IP}
send
NSEOF

echo "Done."
EOF

chmod 755 "$CLIENT_SCRIPT"
success "Example client script written to $CLIENT_SCRIPT"

# ── Quick smoke test ──────────────────────────────────────────────────────────
header "Smoke test — querying ns1.${DOMAIN}"
sleep 1
if dig @127.0.0.1 "ns1.${DOMAIN}" A +short | grep -q "$LISTEN_IP"; then
    success "DNS resolution of ns1.${DOMAIN} works correctly."
else
    warn "Could not resolve ns1.${DOMAIN} — BIND may still be loading. Try: dig @127.0.0.1 ns1.${DOMAIN} A"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}${GREEN}Setup complete!${RESET}"
echo
echo -e "${BOLD}Summary of important files:${RESET}"
echo -e "  BIND config:       /etc/bind/named.conf.options"
echo -e "                     /etc/bind/named.conf.local"
echo -e "  Zone file:         /var/lib/bind/${DOMAIN}.db"
echo -e "  TSIG key (server): /etc/bind/ddns.key"
echo -e "  TSIG key (client): /root/ddns-client.key  ← copy to clients"
echo -e "  Client script:     /root/ddns-register.sh ← copy to clients"
echo -e "  systemd override:  /etc/systemd/system/named.service.d/override.conf"
echo
echo -e "${BOLD}To point hosts at this DNS server, set their nameserver to:${RESET} ${LISTEN_IP}"
echo
echo -e "${BOLD}To register a host manually:${RESET}"
echo -e "  nsupdate -k /root/ddns-client.key <<EOF"
echo -e "  server ${LISTEN_IP}"
echo -e "  zone ${DOMAIN}"
echo -e "  update delete myhostname.${DOMAIN} A"
echo -e "  update add    myhostname.${DOMAIN} 300 A <host-ip>"
echo -e "  send"
echo -e "  EOF"
echo
echo -e "${BOLD}To check BIND status:${RESET}  systemctl status named"
echo -e "${BOLD}To tail logs:${RESET}           journalctl -fu named"
